stages:
  - build
  - test

go-build:
  stage: build
  image: golang:1.23.9
  tags:
    - students-buildkit-medium
  script:
    - git fetch origin $BRANCH
    - git checkout $BRANCH
    - go mod download
    - go mod tidy
    - go build -o auth ./go/cmd/auth

