stages:
  - build
  - test

variables:
  POSTGRES_USER: gitlab_admin
  POSTGRES_PASSWORD: gitlab_password
  POSTGRES_DB: gitlab_db
  PGHOST: db
  SQL_TIMEOUT: 10
  GOCACHE: /go/cache

services:
  - docker:dind

go-build:
  stage: build
  image: golang:1.23.9
  tags:
    - students-buildkit-medium
  script:
    - git fetch origin $BRANCH
    - git checkout $BRANCH
    - go mod download
    - go mod tidy
    - go generate ./...
    - mkdir -p $GOCACHE
    - go build -o auth ./cmd/auth
  cache:
    paths:
      - /go/cache/


test-go:
  stage: test
  image: golang:1.23.9
  tags:
    - students-buildkit-medium
  script:
    - git fetch origin $BRANCH
    - git checkout $BRANCH
    - go mod download
    - go mod tidy
    - go generate ./...
    - mkdir -p $GOCACHE
    - docker-compose up -d bd
    - sleep 20
    - go test -v ./...
  dependencies:
    - go-build
  cache:
    paths:
      - /go/cache/

