services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/data

  auth-service:
    build: 
      context: .
      target: auth
    container_name: auth-service
    environment:
      - DSN=${DSN}
      - SQL_TIMEOUT=${SQL_TIMEOUT}
    ports:
      - "7001:7001"
    depends_on:
      - db
  
  admin-service:
    build: 
      context: .
      target: admin
    container_name: admin-service
    environment:
      - DSN=${DSN}
      - SQL_TIMEOUT=${SQL_TIMEOUT}
    ports:
      - "7002:7002"
    depends_on:
      - db
  
  booking-api:
    build: 
      context: .
      target: web
    container_name: booking-api
    environment:
      - JAVA_SOURCE=${JAVA_SOURCE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - admin-service
      - auth-service

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - booking-api

volumes:
  postgres_data: