services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: 
      - "5432:5432"
    volumes:
      - postgres_data:/data

  grpc:
    build: 
      context: .
      target: grpc
    container_name: grpc
    environment:
      - DSN=${DSN}
      - SQL_TIMEOUT=${SQL_TIMEOUT}
    ports:
      - "7676:7676"
    depends_on:
      - db
  
  booking_service:
    build: 
      context: .
      target: web
    container_name: booking_service
    environment:
      - JAVA_SOURCE=${JAVA_SOURCE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - grpc

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - booking_service

volumes:
  postgres_data: