syntax = "proto3";

option go_package = "internal/pb";
option java_package = "centraluniversity.app.booking";
option java_multiple_files = true;

enum Role {
    ADMIN = 0;
    USER = 1;
}

message SignUpRequest {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
}

message SignUpResponse {
    uint32 id = 1;
    Role role = 2;
    string auth_header = 3;
}

message EmailPassword {
    string email = 1;
    string password = 2;
}

message AuthHeader {
    string auth_header = 1;
}

message UpdateRequest {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    string auth_header = 6;
}

message Empty {}

service Authentication {
    rpc SignUpUser (SignUpRequest) returns (SignUpResponse);
    rpc LogInUser (EmailPassword) returns (AuthHeader);
    rpc UpdateUser (UpdateRequest) returns (AuthHeader);
    rpc DeleteUser (EmailPassword) returns (Empty);
}