syntax = "proto3";

option go_package = "internal/pb";
option java_package = "centraluniversity.app.booking.pb";
option java_multiple_files = true;

enum Role {
    ADMIN = 0;
    USER = 1;
    MAIN_ADMIN = 2;
}

enum By {
    FIRST_NAME = 0;
    SECOND_NAME = 1;
    ROLE = 2;
    NONE = 3;
}

message Empty {}

message UserResponse {
    uint32 id = 1;
    string email = 2;
    string first_name = 3;
    string second_name = 4;
    optional string patronymic = 5;
    Role role = 6;
    string password = 7;
}

service Authentication {
    rpc SignupUser (SignupRequest) returns (UserResponse);
    rpc LoginUser (Email) returns (UserResponse);
    rpc UpdateUser (UpdateRequest) returns (UserResponse);
    rpc UpdatePassword (UpdatePasswordRequest) returns (UserResponse);
    rpc DeleteUser (Email) returns (Empty);
}

message SignupRequest {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
}

message Email {
    string email = 1;
    string password = 2;
}

message UpdateRequest {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    string old_email = 6;
}

message UpdatePasswordRequest {
    string email = 1;
    string old_password = 2;
    string new_password = 3;
}

service AdminService {
    rpc CreateUser (CreateRequestAdmin) returns (Empty);
    rpc GetUser (GetRequestAdmin) returns (GetUserResponseAdmin);
    rpc UpdateUser (UpdateRequestAdmin) returns (UserResponse);
    rpc DeleteUser (DeleteRequestAdmin) returns (Empty);
}

message CreateRequestAdmin {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    string admin_email = 6;
    string admin_password = 7;
}

message GetRequestAdmin {
    By sort_by = 1;
    string sort_key = 2;
    string admin_email = 3;
    string admin_password = 4;
}

message GetUserResponseAdmin {
    repeated UserResponse users = 1;
}

message UpdateRequestAdmin {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    string admin_email = 6;
    string admin_password = 7;
    uint32 id = 8;
}

message DeleteRequestAdmin {
    uint32 id = 1;
    string admin_email = 2;
    string admin_password = 3;
}
