syntax = "proto3";

option go_package = "internal/pb";
option java_package = "centraluniversity.app.booking.pb";
option java_multiple_files = true;

enum Role {
    ADMIN = 0;
    USER = 1;
    MAIN_ADMIN = 2;
}

enum By {
    FIRST_NAME = 0;
    SECOND_NAME = 1;
    ROLE = 2;
    NONE = 3;
    EMAIL = 4;
}

message Empty {}

service Authentication {
    rpc SignupUser (SignupRequest) returns (Id);
    rpc LoginUser (Email) returns (GetResponse);
    rpc UpdateUser (UpdateRequest) returns (Empty);
    rpc UpdatePassword (UpdatePasswordRequest) returns (Empty);
    rpc DeleteUser (Email) returns (Empty);
}

message Id {
    uint32 id = 1;
}

message GetResponse {
    uint32 id = 1;
    string email = 2;
    string first_name = 3;
    string second_name = 4;
    optional string patronymic = 5;
    Role role = 6;
    string password = 7;
}

message SignupRequest {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
}

message Email {
    string email = 1;
    string password = 2;
    uint32 id = 3;
}

message UpdateRequest {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    uint32 id = 6;
}

message UpdatePasswordRequest {
    string email = 1;
    string old_password = 2;
    string new_password = 3;
    uint32 id = 4;
}

service AdminService {
    rpc CreateUser (CreateRequestAdmin) returns (Empty);
    rpc GetUser (GetRequestAdmin) returns (GetResponseAdmin);
    rpc UpdateUser (UpdateRequestAdmin) returns (Empty);
    rpc UpdateRole (UpdateRoleRequestAdmin) returns (Empty);
    rpc DeleteUser (DeleteRequestAdmin) returns (Empty);
}

message CreateRequestAdmin {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    string admin_email = 6;
    string admin_password = 7;
}

message GetRequestAdmin {
    By sort_by = 1;
    string sort_key = 2;
    string admin_email = 3;
    string admin_password = 4;
}

message GetResponseAdmin {
    repeated GetResponse users = 1;
}

message UpdateRequestAdmin {
    string email = 1;
    string first_name = 2;
    string second_name = 3;
    optional string patronymic = 4;
    string password = 5;
    string admin_email = 6;
    string admin_password = 7;
    uint32 id = 8;
    Role role = 9;
}

message UpdateRoleRequestAdmin {
    Role old_role = 1;
    Role new_role = 2;
    string admin_email = 3;
    string admin_password = 4;
    uint32 id = 5;
}

message DeleteRequestAdmin {
    uint32 id = 1;
    string admin_email = 2;
    string admin_password = 3;
}
